apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-app-1
  template:
    metadata:
      labels:
        app: resource-app-1
    spec:
      containers:
      - name: app
        image: nginx
        resources:
          requests:
            cpu: "100m"
