apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-app-8
spec:
  selector:
    matchLabels:
      app: resource-app-8
  template:
    metadata:
      labels:
        app: resource-app-8
    spec:
      containers:
      - name: app
        image: nginx
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
