apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-app-10
spec:
  selector:
    matchLabels:
      app: resource-app-10
  template:
    metadata:
      labels:
        app: resource-app-10
    spec:
      containers:
      - name: app
        image: nginx
        resources:
          requests:
            cpu: "8"
            memory: "16Gi"
          limits:
            cpu: "16"
            memory: "32Gi"
