apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: deprecated_cronjob_13
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: job
            image: busybox
            command: ["echo","hello"]
